#!/bin/bash
/sbin/mount_hfs /dev/disk0s1s1 /mnt1 
ios5=0
if /bin/test -e "/dev/rdisk0s1s2"; then
/sbin/mount_hfs /dev/disk0s1s2 /mnt2
else
ios5=1
/sbin/mount_hfs /dev/disk0s1s3 /mnt2
fi
/bin/rm -f /mnt1/System/Library/LaunchDaemons/com.apple.mobile.softwareupdated.plist /mnt1/System/Library/LaunchDaemons/com.apple.softwareupdateservicesd.plist /mnt1/System/Library/LaunchDaemons/com.apple.OTACrashCopier.plist /mnt1/System/Library/LaunchDaemons/com.apple.OTATaskingAgent.plist 
DataSize="$(/bin/df -B1 | /usr/bin/sed -n -e 's/^.*\/dev\/disk0s1s2 //p' | /usr/bin/sed -e 's/^[ \t]*//' | /usr/bin/sed 's/ .*//')"
GUID="$(/bin/echo -e "i\n2\nq" | /bin/gptfdisk /dev/rdisk0s1 | /usr/bin/sed -n -e 's/^.*Partition unique GUID: //p')"
LastSect="$(/bin/echo -e "i\n2\nq" | /bin/gptfdisk /dev/rdisk0s1 | /usr/bin/sed -n -e 's/^.*Last sector: //p' | /usr/bin/sed 's/ .*//')"
Part2LastSect=$(($LastSect-64))
NewDataSize=$(($DataSize-524288))
Data_Attributeflags="$(/bin/echo -e "i\n2\nq" | /bin/gptfdisk /dev/rdisk0s1 2>/dev/null | /usr/bin/sed -n -e 's/^.*flags: //p')"
if /bin/test "$Data_Attributeflags" = "0001000000000000"; then
/bin/echo -e "d\n2\nn\n\n$Part2LastSect\n\nc\n2\nData\nx\na\n2\n48\n\nc\n2\n$GUID\ns\n4\nm\nn\n3\n\n$LastSect\n\nw\nY\n" | /bin/gptfdisk /dev/rdisk0s1
else
/bin/echo -e "d\n2\nn\n\n$Part2LastSect\n\nc\n2\nData\nx\na\n2\n48\n49\n\nc\n2\n$GUID\ns\n4\nm\nn\n3\n\n$LastSect\n\nw\nY\n" | /bin/gptfdisk /dev/rdisk0s1
fi
/bin/sync;/bin/sync;/bin/sync
/bin/hfs_resize /mnt2 $NewDataSize
if /bin/test "$ios5" = "1"; then
/bin/dd of=/dev/rdisk0s1s4 if=/ramdiskH_beta4.dmg bs=512k count=1
else
/bin/dd of=/dev/rdisk0s1s3 if=/ramdiskH_beta4.dmg bs=512k count=1
fi
/usr/sbin/nvram boot-partition=2
/usr/sbin/nvram -d boot-command
/usr/sbin/nvram -d boot-ramdisk
/usr/sbin/nvram -d wifiaddr
exec /sbin/reboot.real
